swagger: '2.0'
info: 
  title: Bug Demo
  description: Demo of bug
  version: '1.0'
host: localhost
basePath: /
schemes:
  - http
produces:
  - application/json
definitions:
  DemoSub:
    type: object
    description: Child object to body
    properties:
      x:
        type: string
        description: Required string X
      y:
        type: string
        description: Optional string Y
    required: 
      - x
  DemoBody:
    type: object
    description: Demo body object
    properties:
      foo:
        description: Required string property
        type: string
      bar:
        description: Required Enum property
        type: string
        enum:
          - A
          - B
      baz:
        description: optional string property
        type: string
      qux:
        description: optional enum propert
        type: string
        enum:
          - C
          - D
      reqSub:
        $ref: '#/definitions/DemoSub'
      optSub:
        $ref: '#/definitions/DemoSub'
    required:
      - foo
      - bar
      - reqSub
paths:
  '/demo':
    post:
      summary: Demo of bug
      operationId: postDemo
      consumes:  
        - application/json
      parameters:
        - in: body
          name: bodyObj
          description: Body param
          schema:
            $ref: '#/definitions/DemoBody'
          required: true
      responses:
        '200':
          description: OK
        '400':
          description: Invalid
